name: Continuous Integration

on: 
  pull_request:
  push:
    branches:
      - release
      - develop

jobs:
  testing:
    name: Testing
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.2
        with:
          xcode-version: latest-stable
      - name: Build module
        run: swift build -v
      - name: Test module
        run: swift test -v
